name: topacy-static
static_sites:
- name: topacy-static
  github:
    branch: master
    deploy_on_push: true
    repo: slothturtlesnail/topacy
  source_dir: public
  output_dir: public
  routes:
  - path: / 